"""init

Revision ID: 934bb26d852a
Revises: 
Create Date: 2026-03-10 02:46:46.366839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934bb26d852a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'player1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('matches_player1_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_winner_id_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_player2_id_fkey', 'matches', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('matches_player2_id_fkey', 'matches', 'users', ['player2_id'], ['id'])
    op.create_foreign_key('matches_winner_id_fkey', 'matches', 'users', ['winner_id'], ['id'])
    op.create_foreign_key('matches_player1_id_fkey', 'matches', 'users', ['player1_id'], ['id'])
    op.alter_column('matches', 'player2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'player1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
