services:

  db:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    container_name: db
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
<<<<<<< 32-feat-login-page
      context: .
      dockerfile: services/backend/Dockerfile
=======
      context: ./services/backend
      dockerfile: Dockerfile
>>>>>>> develop
    container_name: backend
    environment:
      DB_HOST:      ${DB_HOST}
      DB_PORT:      ${DB_PORT}
      DB_USER:      ${DB_USER}
      DB_PASSWORD:  ${DB_PASSWORD}
      DB_NAME:      ${DB_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
<<<<<<< 32-feat-login-page
    volumes:
      - ./src/backend:/app
=======
>>>>>>> develop
    networks:
      - transcendence_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
<<<<<<< 32-feat-login-page
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
=======
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
>>>>>>> develop
    networks:
      - transcendence_network
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    environment:
      BACKEND_PORT:  ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      DOMAIN:        ${DOMAIN}
    ports:
      - "443:443"
    networks:
      - transcendence_network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db_data:

networks:
  transcendence_network:
    driver: bridge
