"""add_unique_constraint_to_chat_rooms_room_name

Revision ID: 7c535259ee74
Revises: 0cabf8b06af6
Create Date: 2026-03-16 01:58:17.847042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c535259ee74'
down_revision: Union[str, None] = '0cabf8b06af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_rooms', 'room_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint('uq_chat_rooms_room_name', 'chat_rooms', ['room_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_rooms_room_name', 'chat_rooms', type_='unique')
    op.alter_column('chat_rooms', 'room_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
