"""add_from_user_id_to_notifications

Revision ID: a1b2c3d4e5f7
Revises: d8fcaa003ff3
Create Date: 2026-04-12 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: Union[str, None] = 'd8fcaa003ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_notifications_from_user_id_users', 'notifications', 'users', ['from_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_from_user_id_users', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'from_user_id')
    # ### end Alembic commands ###
