"""add_avatar_url_and_display_name_to_users

Revision ID: 43bafb48a1a7
Revises: efba15a36898
Create Date: 2026-03-11 01:40:17.804717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bafb48a1a7'
down_revision: Union[str, None] = 'efba15a36898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
