"""add_avatar_url_and_display_name_to_users

Revision ID: efba15a36898
Revises: d7ad2f503e4e
Create Date: 2026-03-11 01:21:32.888499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efba15a36898'
down_revision: Union[str, None] = 'd7ad2f503e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
